apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- deployment.yaml
- core/clusterbindingrole.yaml
- core/homepage-configmap.yaml
- core/secrets.yaml
- core/service.yaml
- core/serviceaccount.yaml
- core/namespace.yaml
