apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- core/deployment.yaml
- core/config-map.yaml
- core/service.yaml
- core/namespace.yaml
- core/serviceaccount.yaml
